version: '3.4'

services:

  db:
    image: postgres:11.10
    volumes:
      - /tmp/lima/streams_exp:/var/lib/postgresql/data/
    ports:
      - "0.0.0.0:5432:5432"

    environment:
      POSTGRES_DB: streams_exp
      POSTGRES_PASSWORD: password
